# Generated by Django 3.2.4 on 2021-07-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0002_auto_20210717_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sales_channel',
        ),
        migrations.AddField(
            model_name='item',
            name='sales_channel',
            field=models.CharField(default='Generic Sale', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoices.invoice'),
        ),
    ]
