# Generated by Django 3.2.4 on 2021-07-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Invoices', '0003_auto_20210720_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(related_name='proditem', through='Invoices.Item', to='Inventory.Product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoices.invoice'),
        ),
    ]
