# Generated by Django 3.2.4 on 2021-07-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0004_auto_20210721_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoices.invoice'),
        ),
    ]
