# Generated by Django 3.2.4 on 2021-07-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecord',
            options={'verbose_name': 'Product'},
        ),
    ]
