# Generated by Django 3.2.4 on 2021-07-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_productrecord_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrecord',
            name='date_sold',
        ),
    ]
